version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/tasksdb
    depends_on:
      - db

  db:
  image: mongo
  environment:
    - MONGO_INITDB_DATABASE=tasksdb
  volumes:
    - db_data:/data/db
    - ./init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  db_data: