version: '3.8'

services:
  app:
    image: abdelazez1/lab6-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/tasksdb
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - db_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  db_data: